### ISSUE TITLE
No module named 'anime_dl'

### ISSUE THREAD

**Issue by Haejien** [Xonshiz/anime-dl#1]
I don't know if you're still in the process of writing this but I get a 

`No module named 'anime_dl'`

Full error:

```
'Traceback (most recent call last):
  File "AnimeDL.py", line 9, in <module>
    import anime_dl.sites
ModuleNotFoundError: No module named 'anime_dl''
```

**Comment by Xonshiz** [comment]
Which version of script are you using? `Windows Binary` or `Python`?
If `Python`, then which `Python Version`? Because this script only supports `Python 3`, as mentioned in the [ReadMe](https://github.com/Xonshiz/anime-dl#python-support)

**Comment by Haejien** [comment]
I will admit that I initially ran the script with 2.7, however I did run it with python3 after. I also tried using the binary but it runs but there's nothing to indicate what happens, e.g no verbose to see what's going on and why it closed with no text.

**Comment by Xonshiz** [comment]
Yep, verbose isn't supported in this one right now. I found why these things are happening with the Python Script. Updating it all right now.
