### ISSUE TITLE
--skip not working

### ISSUE THREAD

**Issue by lawlaw2** [Xonshiz/anime-dl#10]
Hi, i've try do download all subtitle from 12 episodes without the vidéo but the argument "--skip" is unrecognized. 

here the code I use

`@echo off
set /p lien= Entrer le lien 
echo %lien%
pause
anime-dl.exe  -i "%lien%" -u "*****" -p "*****" -r "720" --skip -l "french" 
pause`

**Comment by Xonshiz** [comment]
Please check the [ReadMe](https://github.com/Xonshiz/anime-dl#reporting-issues) and see [How to Post Issues](https://github.com/Xonshiz/anime-dl#reporting-issues) and re-format your query accordingly.

And make sure that you're using the latest version, i.e., 2017.04.17.

**Comment by lawlaw2** [comment]
HI, i have the last version donwload few hours ago.

Command line executed : 
`anime-dl.exe  -i "http://www.crunchyroll.com/izetta-the-last-witch" -u "***" -p "***" --skip -r "720"  -l "french"`

--verbose can't create the errorlog because the command line is not executed : 

This is the error : 

`usage: anime-dl.exe [-h] [--version] [-p PASSWORD] [-u USERNAME] [-i INPUT]
                    [-r RESOLUTION] [-l LANGUAGE]
anime-dl.exe: error: unrecognized arguments: --skip`

**Comment by Xonshiz** [comment]
drop the "-r" and "-l" arguments and you're using the "-l" argument wrong. Language is not for the subtitles, it's for the audio. And when you provide the "--skip" argument, there's no need for the resolution to be passed. And if you want to download 720p, you don't need to pass the resolution's argument at all.

Please check the Issue #5 for the similar issue on resolution.

**Comment by Xonshiz** [comment]
Are you sure you're using the current version? I just ran your command and it did NOT give me the error about `--skip` not being recognized.

Run this command : 

```
anime-dl.exe --version
```

And share the output.

Btw, what did you mean by `--verbose can't create the errorlog because the command line is not executed :` ?

**Comment by lawlaw2** [comment]
problem is resolved ;) thanks for help
