### ISSUE TITLE
Not Implemented Error

### ISSUE THREAD

**Issue by tantalizingbana** [Xonshiz/anime-dl#105]
I have Windows 10 and I have ffmpeg and nodejs executables in the same directory as the anime-dl binary. Running this command in powershell:

`.\anime_dl.exe -i "https://www.funimation.com/shows/sword-art-online/the-world-of-swords/uncut/?lang=english&a=1" -u "user@user.com" -p "supersecretpassword" -r "1080p"`

Just produces a cryptic error message:

`Not Implemented`

So what's going on?

**Comment by Xonshiz** [comment]
The error is not cryptic. I've not implemented download for Funimation yet. Just crunchyroll as of now.

**Comment by BittahBandit1** [comment]
When are you going to implement Funimation downloading?
