### ISSUE TITLE
<body bgcolor=white>: Invalid argument

### ISSUE THREAD

**Issue by amirnoxik** [Xonshiz/anime-dl#12]
hi 
i get this error : <body bgcolor=white>: Invalid argument

Command Line Arguments You Gave :
__main__.py -i "http://www.crunchyroll.com/yowamushi-pedal-new-generation/episode-17-733929" -u "amirnoxik" -p "xxxxxxxx" -r "720p" -v 

Verbose Log Link 
https://gist.github.com/amirnoxik/c6816a2bb1ec1b4a332fe5d8e4807bd1

Long Explanation : when i want to download this anime i get <body bgcolor=white>: Invalid argument

**Comment by Xonshiz** [comment]
Judging from the verbose log, everything seems fine till [Line 422](https://gist.github.com/amirnoxik/c6816a2bb1ec1b4a332fe5d8e4807bd1#file-verbose-L422), but error comes up on [Line 425](https://gist.github.com/amirnoxik/c6816a2bb1ec1b4a332fe5d8e4807bd1#file-verbose-L425). I'll take a look at this issue in a day or two.

**Comment by amirnoxik** [comment]
okey no probleme thank you

**Comment by Xonshiz** [comment]
Issue fixed!
