### ISSUE TITLE
Error Sub ok - but no video (rtmpDL)

### ISSUE THREAD

**Issue by lawlaw2** [Xonshiz/anime-dl#13]
Hi ! Since today subtitle are donwloaded correctly but not the video file. 

Error: 
UnboundLocalError: local variable 'rtmpDL' referenced before assignment
Failed to execute script __main__

error log : 

[Error Log.txt](https://github.com/Xonshiz/anime-dl/files/979306/Error.Log.txt)

**Comment by Xonshiz** [comment]
I just tried to download the video and it downloaded just fine. Please try again later. Are you sure that you're a premium member? try downloading a 360p video.

**Comment by lawlaw2** [comment]
Ok, I've done a complete re-install of all dependencies and your projet and it work. I do not know what happened because I didn't touch anything before the bug.

Thanks for your help ;)

**Comment by Xonshiz** [comment]
It's not your, it's not the script. It's the Crunchyroll itself. Their streams are weirdly delivered. Some streams seem to have hls, some have rtmp streams as options... and some have both.
