### ISSUE TITLE
No subtitles for 1 episode.

### ISSUE THREAD

**Issue by xxxKaiserxxx** [Xonshiz/anime-dl#14]
Hello,

I'm trying to download this episode:

http://www.crunchyroll.com/the-royal-tutor/episode-6-at-caf-mitter-meyer-733971

anime-dl.exe -i "http://www.crunchyroll.com/kado-the-right-answer/episode-6-tetrok-734137" -u "xxxx" -p "xxxx" -r "1080"

For some reason I can't get the subtitles.

I have tried to download a different episode/title and it works just fine.

Any idea?

This is my Error Log:

https://gist.github.com/xxxKaiserxxx/8aaf50ffaebbcaf1f5e56e636aeccd60

**Comment by Xonshiz** [comment]
I tried this on my end and it worked just fine. Grabbed 4 subtitle files. Double check your premium account. There are no subs for logged out user, or so it seems. I haven't updated the logging for login check. I have to update the whole script to make it more robust, which I'll do next month. Till then, please grab the subs from somewhere else or, just wait for 2 weeks.

**Comment by xxxKaiserxxx** [comment]
This is weird. I just tried to re-download it and it's working just fine. I got all the subtitles.

My account is logged-in all the time because I rarely shut down my pc.

It would be great to have that feature and I can't wait to see it out. /cheer

Thank you so much Xonshiz for your amazing work.

**Comment by Xonshiz** [comment]
Uh. Just a word of advice... log out of your account from everywhere before using the script. Cloudflare is a bitch and sometimes if it detects multiple sessions for an account from same/various IPs, it can block your requests. Since this seems to be an issue on crunchyroll's side, I'll be closing the issue.
