### ISSUE TITLE
Hardsubbed video.

### ISSUE THREAD

**Issue by xxxKaiserxxx** [Xonshiz/anime-dl#16]
Hello,

I'm trying to download this file: 

http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285

but instead of getting a raw video file and subtitle files as usual I get a hardsubbed video file.

I used this command:
anime-dl.exe -i "http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285" -u "xxxxx" -p "xxxxx" -r "1080"

This is the error file:
https://gist.github.com/xxxKaiserxxx/64bed07a24859acdd0ab34457422813b

I don't use mkvmerge.exe because I like mp4 output more than mkv.

Thank you.

**Comment by Xonshiz** [comment]
Okay, first thing.... This script spits out multiple subtitles and merges it into  one .mkv file.

.mp4 doesn't support multiple streams. One one sub at max.
.mkv supports as many streams as you can give it.

I'll look into this hardsubbed thing though.

**Comment by xxxKaiserxxx** [comment]
I see. I'll use it then.

I think my issue fixed itself, I can download the raw file now. <3

**Comment by Xonshiz** [comment]
Then I guess it was just crunchy being a bitch. Sometimes this happens. Some other user also mentioned the same issue on streams sometimes. This can happen mostly when the episode is released.

I mean, like they released the episode and you tried to download it. Their streams can take upto 30 minutes to behave properly. And some streams are just fine.weird.
Should I close this issue then? Let me know :D

**Comment by xxxKaiserxxx** [comment]
Yeah I think so too.

Yes everything is good now <3 Thank you ^.^
