### ISSUE TITLE
Could not log in because special character on PW

### ISSUE THREAD

**Issue by MrDonGato** [Xonshiz/anime-dl#17]
Command Line Arguments You Gave : 

D:\animu>anime-dl.exe -i "http://www.crunchyroll.com/angels-3piece/episode-3-the-boy-on-hiatus-descends-and-flees-and-the-girls-from-the-church-742989" -u "xxxxx" -p "**[password contains ñ]**" --skip
Will be skipping video downloads
Trying to login...
Unable to Log you in. Check credentials again.
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 19, in <module>
  File "anime_dl\__main__.py", line 73, in main
  File "anime_dl\AnimeDL.py", line 29, in __init__
  File "anime_dl\sites\crunchyroll.py", line 46, in __init__
TypeError: 'NoneType' object is not iterable
Failed to execute script __main__

Long Explanation : I try to log in to download only subtitles, but i get everytime this error. Tried also with an account without **ñ** and it worked perfectly. That's the only difference between accounts.

**Comment by Xonshiz** [comment]
Should be fixed now.
