### ISSUE TITLE
Download Error# Using Linux

### ISSUE THREAD

**Issue by Rovnost** [Xonshiz/anime-dl#18]
maxify@maxify-computer:~/anime-dl-master/anime_dl$ python __main__.py -i "http://www.crunchyroll.com/boruto-naruto-next-generations/episode-16-crisis-the-threat-of-failing-740237" -u "XXX" -p "XXX" -r "1080p" --verbose
Trying to login...
Logged in successfully...
Downloading Boruto Naruto Next Generations - 16 [1920x1080].enUS.ass ...
Downloading Boruto Naruto Next Generations - 16 [1920x1080].ptBR.ass ...
Downloading Boruto Naruto Next Generations - 16 [1920x1080].arME.ass ...
Downloading Boruto Naruto Next Generations - 16 [1920x1080].itIT.ass ...
Downloading Boruto Naruto Next Generations - 16 [1920x1080].deDE.ass ...
Couldn't connect to the m3u8 file download link...
[Errno 2] No such file or directory
maxify@maxify-computer:~/anime-dl-master/anime_dl

**Comment by Xonshiz** [comment]
This has been fixed. Please check on your end.
