### ISSUE TITLE
Error: "can't use a string pattern on a bytes-like object"

### ISSUE THREAD

**Issue by UiharuKazari2008** [Xonshiz/anime-dl#20]
Hi am trying run it but all i get is this

root@Awatsuki:/opt/awatsuki-anidps/anime_dl# python3 __main__.py -i "http://www.crunchyroll.com/i-cant-understand-what-my-husband-is-saying/episode-13-happy-days-678059" -u "g" -p "g" -r "1080p"
Trying to login...
Logged in successfully...
Seems like this video isn't available...
can't use a string pattern on a bytes-like object

**Comment by UiharuKazari2008** [comment]
I belive its getting tripped  up here sense it never logs the line after 
m3u8_file_link = str(re.search(r'<file>(.*?)</file>', xml_page).group(1)).replace("&amp;", "&")

**Comment by Xonshiz** [comment]
Will check it by the end of this week.

**Comment by Xonshiz** [comment]
Just checked on my end and it's working just fine. It downloaded the same episode and muxed it properly.

Refer to the screenshot : 

https://i.imgur.com/WB1Ri5g.png

Closing this, as I couldn't replicate the issue.
