### ISSUE TITLE
Suggestion:  Requirements.txt

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#21]
I would like to suggest adding the following to "requirements.txt" so that users may make their own .exe with your batch file.  I just reinstalled Windows, Python 3.6 x64, node, etc. and thse were the only 3 items I needed in addition to what you already had in the requirements file.  Optionally, you could make a "Build_Requirements.txt" and dump them in there.

```
pyinstaller
bs4
tqdm
```
Thanks for the script.  It does what it needs to.

**Comment by Xonshiz** [comment]
For making `.exe`, PyInstaller isn't the only option. `Py2exe`, `cx_freeze` or `nuitka`, there are many choices. Hence, I'm not adding that one. But thanks for reminding about `bs4` and `tqdm`.

Fixed it!
