### ISSUE TITLE
Could not find the show links

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#22]
**Command Line Arguments:**  
`anime-dl.exe -i http://www.crunchyroll.com/i-cant-understand-what-my-husband-is-saying  -u xxxxxx -p xxxxxx -v`
**Verbose Log Link:**
`https://pastebin.com/KKnvXr74`
**Long Explanation:**
```
This should have downloaded every episode of the show in the link as stated in the example syntax.
What happened was the script was unable to find any links and therefore it did not download anything.
Had I linked an individual episode's page, it would download that single episode's link but nothing more.
To restate the issue, single Episode URLs function, "Whole Show" URLs do not detecting links and
therefore will not download episodes.  After logging in with a "Whole Show" link, CMD window states:
"Could not find the show links."
```

That about sums it up.

**Comment by Xonshiz** [comment]
Thank you for reporting. I've checked it on my end and have issued and update for the same. It should work now. Please do check on your end and get back to me, if there's any problem or anything needs an update.

**Comment by leptoid** [comment]
Yep.. you found the bug.  Thanks for the help and quick response!
