### ISSUE TITLE
Seems like this video isn't available... cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by MetaVulpes** [Xonshiz/anime-dl#27]
**Command Line Arguments You Gave** : python3.6 __main__.py -i "http://www.crunchyroll.com/dragon-ball-super/episode-1-the-peace-reward-who-will-get-the-100-million-zeni-723163" -u "xxxxx" -p "xxxxx" -r "1080p" -l "sub" -v

**Verbose Log Link** : https://pastebin.com/iS9tK27k

**Long Explanation** : Been trying this with multiple anime and with/without the language argument. Can't seem to get it to work at all with any anime on the site. Read the debugging log, seems like it isn't able to grab the video file for some reason.

**Comment by Xonshiz** [comment]
Hey! If you're using Python 3.6, this won't work. It has some internal problems while working with 3.6.
I've tried with python 3.5, it works on that. Plus, it should be "**__main__.py**" and not just "**main.py**".

And, you don't have to specify the "-l"  option, specially for a single video. Get Python 3.5 or 2.7 and run : 

>python3.5 __main__.py -i "http://www.crunchyroll.com/dragon-ball-super/episode-1-the-peace-reward-who-will-get-the-100-million-zeni-723163" -u "xxxxx" -p "xxxxx" -r "1080p
