### ISSUE TITLE
Can't download anything (503 error)

### ISSUE THREAD

**Issue by WiZeeFR** [Xonshiz/anime-dl#31]
First, thanks for ur script, it's very nice to use.

2 days ago, I was trying to download some anime with ur script but I get a 503 error, there is the full error code.

> Will be skipping video downloads
> Trying to login...
> Couldn't connect to the login page...
> Website returned : 503
> Traceback (most recent call last):
>   File "anime_dl\__main__.py", line 19, in <module>
>     class main(object):
>   File "anime_dl\__main__.py", line 70, in main
>     if type(args.range) == list:
>   File "anime_dl\AnimeDL.py", line 29, in __init__
>     url=url[0], password=password, username=username, resolution=resolution, language=language, skipper=skipper, logger = logger, episode_range=episode_range)
>   File "anime_dl\sites\crunchyroll.py", line 46, in __init__
>     cookies, Token = self.webpagedownloader(url=url, username=username[0], password=password[0])
> TypeError: 'NoneType' object is not iterable
> Failed to execute script __main__

Did I miss something or Crunchyroll patched it ? 

Thanks.

**Comment by Xonshiz** [comment]
Seems like crunchy or Cloudflare made some changes somewhere. Will take time to check it out.

**Comment by WiZeeFR** [comment]
@Xonshiz I see, thanks for your work! Hope u'll resolve this.

**Comment by leptoid** [comment]
The error has changed... I was getting the same as him.  Tried on 2 machines where it was working fine before.
```
c:\_bin\anime-dl>anime-dl -u private -p private -r 480p -i http://www.crunchyroll.com/black-clover/episode-15-the-diamond-mage-758893
Trying to login...
Couldn't connect to the login page...
Website returned : 503
Traceback (most recent call last):
  File "anime_dl\__main__.py", line 19, in <module>
  File "anime_dl\__main__.py", line 73, in main
  File "anime_dl\AnimeDL.py", line 29, in __init__
  File "anime_dl\sites\crunchyroll.py", line 46, in __init__
TypeError: 'NoneType' object is not iterable
Failed to execute script __main__

c:\anime-dl>
```

**Comment by Xonshiz** [comment]
Guys, please do check the latest push. Things should've been fixed now. They're working on my end. If you're trying this behind a proxy, then try without proxy and check.

**Comment by mynameisyo** [comment]
hey  , i got problem when download finished i cant find the episode on folder 'output' 
and i got this message https://imgur.com/NEuZjRd.jpg

**Comment by leptoid** [comment]
@Xonshiz - You got it.  It is working now.   Thanks!

**Comment by leptoid** [comment]
@mynameisyo - that is a different type of error and would require a new thread.  This thread is about something totally different.

**Comment by mynameisyo** [comment]
@leptoid , now it works fine with me somehow lol

**Comment by leptoid** [comment]
It is an issue with subs.  Only happens with some.  I will make a new post for it.

**Comment by Xonshiz** [comment]
I've tried downloading some videos from crunchyroll before posting and it's working just fine for me. That error relating to "ar" is an error in mkvmerge.exe command. I think I've got the wrong language code for arabian as ar.

**Comment by leptoid** [comment]
Yeah, it is arabic subtitle related.  I was troubleshooting it today while writing a 8 page college paper containing 3 corporate policies.  gah... 
essentially, anytime a subtitle with `arME.ass` is downloaded, it won't mux.  It errors and continues on with the script by deleting.  Not all shows have it which is why @mynameisyo say sit is working now.
Here are some that do:
Boruto
The Ancient Magus
Darling In The Franxx

I planned on looking at the code later, seeing if I can "learn to code like a champion!" and fix that part.  I can't code... though I have had some programming so I understand parts, and I can repair parts sometimes.
I will let you know here if I figure something out.  Otherwise, if people delete the "arME.ass" subtitle file before it tries to multiplex, it all works fine.

**Comment by Xonshiz** [comment]
Thanks for the detailed Info. I just need to fix one thing and it'll work. I'll cross check this on my end and will release an update in a day or so.

**Comment by Xonshiz** [comment]
@leptoid  could you please open a new issue for this Arabic subs thing? This #31 has been fixed and arabic subs problem is a different problem. It's hard to remember which issue is where.
