### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by moi15moi** [Xonshiz/anime-dl#34]
Hi,

I have a problem with the installation at the step 4

1.) Make sure you have Python installed and is present in your system's path.

2.) Grab FFmpeg from this link, Node.js from this link and RTMPDump.

3.) Install FFmpeg and Node.js and place it in the directory of this script, or put them in your system's path.

4.) Browse to the directory of this script and open command prompt/shell in that directory and run this command :

python pip install -r requirements.txt

In my cmd I wrote : C:\Users\smokerlolilol>cd "C:\Users\smokerlolilol\Desktop\anime-dl-master"

After, I wrote : C:\Users\smokerlolilol\Desktop\anime-dl-master>python pip install -r requirements.txt

Where is the problem ?

Sorry for my bad english :(

And thank you

**Comment by Xonshiz** [comment]
What is the error you got after this? If you're following these steps properly, there shouldn't be any problem. Please share the error details..

**Comment by moi15moi** [comment]
It just doesn't find the good file. I am pretty sure that I make an mistake somewhere but I don't know where

![capture](https://user-images.githubusercontent.com/34408507/35179767-b599c414-fd6e-11e7-83ef-f3e123fc7ee6.JPG)


It's in french sorry

**Comment by Xonshiz** [comment]
could you please translate the error from french to english for me? and also, type "dir /s" to see the list of files in the folder. Share the screenshot please.

**Comment by moi15moi** [comment]
C:\Users\smokerlolilol>cd "C:\Users\smokerlolilol\Desktop\anime-dl-master"

C:\Users\smokerlolilol\Desktop\anime-dl-master>python pip install -r requirements.txt
'python' is not recognized as an internal command 
or external, a executable file ou un  command file.

C:\Users\smokerlolilol\Desktop\anime-dl-master>

**Comment by Xonshiz** [comment]
you don't have Python installed.That's what I thought. The error clearly states that you don't have python installed. 
If you have installed python, make sure it's in your system path. Plus, if you're on windows, I'd recommend that you use windows binary from the releases section. You don't have to install Python or it's library dependencies. You just need NodeJS and the windows binary and it'll do the job.

**Comment by moi15moi** [comment]
Can you explain to me what is the system path please. I don't know what it mean in french

**Comment by Xonshiz** [comment]
Installing python or other dependencies could be tricky. So, if you're not into these things, I'd recommend that you don't touch python at all. This goes for windows users because you need to setup python in your system.

Please read this section carefully : https://github.com/Xonshiz/anime-dl#installation

I'd recommend that you don't install python at all.

Now, if you really want to install Python, and use this script with python instead, you can follow this tutorial step by step: 

https://www.youtube.com/watch?v=dX2-V2BocqQ

**Comment by moi15moi** [comment]
So you says to me that it should be ok for me like that ?

![image](https://user-images.githubusercontent.com/34408507/35179877-82bde978-fd71-11e7-8664-720ebc02bd57.png)

**Comment by Xonshiz** [comment]
have you installed NodeJS properly  in your system? move the ffmpeg.exe inside the folder where anime-dl.exe is.

**Comment by moi15moi** [comment]
Like that

![image](https://user-images.githubusercontent.com/34408507/35179920-6de3ffe6-fd72-11e7-8dfc-c4801faf0f08.png)

**Comment by Xonshiz** [comment]
Install nodejs. Is that node.exe file the installed or the portable nodejs.exe?

**Comment by moi15moi** [comment]
When I open it

![image](https://user-images.githubusercontent.com/34408507/35179937-cfe62b38-fd72-11e7-9fb2-f8ff6ee28f68.png)

**Comment by Xonshiz** [comment]
This should do it then. Try running anime-dl now. However, it would be down, as mention in #31 . Crunchyroll or Cloudflare have changed a few things.

**Comment by moi15moi** [comment]
![image](https://user-images.githubusercontent.com/34408507/35179955-5dece0de-fd73-11e7-8d13-806992b5423b.png)

**Comment by moi15moi** [comment]
It crash. I opened it and it crash

**Comment by Xonshiz** [comment]
This is a command line program. Please look it over internet. Setting up the program and getting it running and all that is not something I can do for everyone. Please look it up on internet.

**Comment by moi15moi** [comment]
I was thinking it was like that but I didn't made it. Thank you for the help

![image](https://user-images.githubusercontent.com/34408507/35180056-5e35bd48-fd75-11e7-8c02-8fc548d865dd.png)
