### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by OgnistyPoland** [Xonshiz/anime-dl#35]
without xvidcore: http://s6.ifotos.pl/img/2018-01-2_qnphrsn.png
with: http://s5.ifotos.pl/img/2018-01-2_qnphrse.png

**Comment by Xonshiz** [comment]
I cannot understand the error. But, you need ffmpeg in the directory of this script or in the system's path. All the installation and usage instructions are mentioned in the readme for the different operating systems, I cannot help further. Sorry.
