### ISSUE TITLE
whats happen

### ISSUE THREAD

**Issue by mynameisyo** [Xonshiz/anime-dl#37]
hey  when i tried to download episodes i got this message https://imgur.com/H0ctCy1 and i found out that 
anime-dl.exe has faded  also i cant download it 
i tried this on two pc and the same result

**Comment by Xonshiz** [comment]
Have you installed ffmpeg and nodejs? Have you read the read me file? Please go through the read me file thoroughly and follow the instructions. If you have any issues even after that, please re-open this issue by noting down the issue(s) as specified in the read me. You should also run the anime-dl.exe with --verbose command, if anything wrong happens or the app crashes and then upload that error log here.

Here's the Read Me File : https://github.com/Xonshiz/anime-dl/blob/master/ReadMe.md

**Comment by mynameisyo** [comment]
the program where work fine with me but today when i tried to download 
it wont work

**Comment by Xonshiz** [comment]
Yeah, and I need a detailed information about various things. I cannot troubleshoot based on the information you've provided. Please re-read the read me and fill in the details. I need the error log, I need the command you gave, I need to know whether you have nodejs and ffmpeg in  your path. 

Is that show available in your region? Is your account still valid? There are lots of things I need to know. So, until unless you tell me about them, I can't look into this.

**Comment by mynameisyo** [comment]
yes i have all this things and as i told u 
the program were working fine with me till today 
this proof : https://imgur.com/a/z5Q69.jpg
https://imgur.com/ahTU8ys.jpg
but the anime-dl has romeved and i cant download it

**Comment by mynameisyo** [comment]
i dont know why the system is deleting the exe file 
can you help me

**Comment by Xonshiz** [comment]
Your antivirus might be removing it thinking that it's a virus.
