### ISSUE TITLE
problem exe file

### ISSUE THREAD

**Issue by moze01** [Xonshiz/anime-dl#38]
hey i did download all programes you wrote in 'ReadMe' but i can't download 'anime-dl.exe'  
when i try to download it the antivirus will removed could you please tell me how to fix it?

**Comment by Xonshiz** [comment]
Hey, I think that your antivirus is thinking that anime-dl.exe is a virus and is deleting it. A fix would be to add an exception in your antivirus for anime-dl.exe. Or, if you really want to kill yourself, you could try installing python ;)
