### ISSUE TITLE
Arabic Subtitles Cause Script to Fail/Incorrectly Handled

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#39]
When an episode of a show with subtitle `arME.ass` is downloaded, subs and video mux. Script errors and continues on with the next function of the script which is deleting all temp files (note - nothing is moved to output). Not all shows have these which is why error seems intermittent between shows.
Here are some that do:

```
Boruto
The Ancient Magus
Darling In The Franxx
```

Delete the `arME.ass` subtitle file before scripts attempt to multiplex subtitles with video allows everything to mux correctly, due to the incorrectly handled subs no longer being a factor.

**Comment by Xonshiz** [comment]
Thanks for creating the new issue. Noted.

**Comment by Xonshiz** [comment]
Shouldn't cause more problems now. Updated windows binary released, check on your end please.

**Comment by leptoid** [comment]
Will let you know what I find out.  Will edit this as soon as I know.

**Comment by Xonshiz** [comment]
Thanks for the confirmation :)
