### ISSUE TITLE
hi please help with this : Please enter the required arguments

### ISSUE THREAD

**Issue by amirnoxik** [Xonshiz/anime-dl#4]
hi 
why i get this msg 
Please enter the required arguments __main__.py --help

**Comment by Xonshiz** [comment]
Please go through the "[ReadMe]()" thoroughly before using this script. There you will find the [Usage Section](https://github.com/Xonshiz/anime-dl#usage) and everything else you need to know to run this script.

There, you will find a section which reads "[Reporting Issues](https://github.com/Xonshiz/anime-dl#opening-an-issuerequesting-a-site)" and follow it.

I'm closing this one, as it's not a script issue.

**Comment by amirnoxik** [comment]
i read it all 
and try everything 
but the same prblm :(

**Comment by Xonshiz** [comment]
Doesn't look like you've read it properly. Because you still haven't fixed your explanation.

Please read [how to report issue](https://github.com/Xonshiz/anime-dl#opening-an-issuerequesting-a-site) and format your query.

**Comment by amirnoxik** [comment]
aha I understand you now
okey no prblm thank you
