### ISSUE TITLE
Enhancement - Recursive Folders for each Anime

### ISSUE THREAD

**Issue by leptoid** [Xonshiz/anime-dl#46]
Anime-DL currently downloads shows in the main folder and then moves objects to a subfolder named "Output".  How much effort would it take to send episodes to Output\[Anime Title]?

The function which moves objects to Output would need modified to check/verify folder [Anime Title] existed, and then send objects to the respective recursed folder.

As an example:
http://www.crunchyroll.com/naruto/episode-220-departure-535236 would be sent to "\Output\naruto\[episode]"
while 
http://www.crunchyroll.com/darling-in-the-franxx/episode-10-the-city-of-eternity-759593 would be sent to "\Output\darling-in-the-franxx\[episode]"

To improve efficiency, Anime-DL could also check the respective show's folder for the episode(s) so that it does not download a show that already exists.  I believe it does this with the Output folder now, except it downloads before the verification and leaves the downloaded file in folder "\Anime-DL\" if "\Output\" already contains the file.

If I ever had time, I would consider looking into doing this modification as most of it only requires optimizing/modifying existing code.  Unfortunately, real life gets in the way.

**Comment by Xonshiz** [comment]
It is easy to do, but like you mentioned, real life gets in the way. I'm currently a little too busy to give my attention to this. But, I'll try to get something done soon.
