### ISSUE TITLE
Please enter the required arguments. Run __main__.py --help

### ISSUE THREAD

**Issue by amirnoxik** [Xonshiz/anime-dl#5]
Subject :
 Please enter the required arguments. Run __main__.py --help

Command Line Arguments You Gave : 
 __main__.py -i "<http://www.crunchyroll.com/the-royal-tutor/episode-1-the-royal-tutor-arrives-733961>" -u "my username" -p "my password" -r "default"

Long Explanation : 
I have done all the steps. but , when i want to start downloading using Python Script, I enter the line argument Above, The download should begin, but i get this msg 
`Please enter the required arguments. Run __main__.py --help`
the same msg i see when i open anime-dl.exe

**Comment by Xonshiz** [comment]
you don't have to specify the `-r` argument if you want `720p`. `default = 720p` denotes that if you don't pass the `-r` argument, that is what the script will take.

And if you're using the python script, you need to call `__main__.py`, instead of `main.py`. So, your command should be like : 

````
__main__.py -i "http://www.crunchyroll.com/the-royal-tutor/episode-1-the-royal-tutor-arrives-733961" -u "my username" -p "my password"
````

**Comment by amirnoxik** [comment]
same : `Please enter the required arguments. Run __main__.py --help`
what is the 
> the required arguments !!

**Comment by amirnoxik** [comment]
i'm using python 3.6

**Comment by Xonshiz** [comment]
Please give me a minute to confirm this on my end.

**Comment by amirnoxik** [comment]
okey take ur time sir

**Comment by Xonshiz** [comment]
I just ran this on my Python 3.5 and it's running just fine. Check here : 

https://preview.ibb.co/b3FaQk/Clipboard_image_2017_04_09_19_10_33.png

**Comment by amirnoxik** [comment]
mmmm 
i will delete everything and try again

**Comment by Xonshiz** [comment]
No, wait. I have python 3.6 as well. Let me try on it as well.

**Comment by amirnoxik** [comment]
okey i'm waiting

**Comment by Xonshiz** [comment]
Okay, so I checked it on Python 3.6 and it's working. It's not showing the argument error, as it's showing you. However, there's some other internal script error that it's showing. So, I will advice you to install Python 3.5 as well in your environment and run this script via that, at least for the time being. I'm afraid that I'm a little busy till June. But, I'll try to port this on Python 3.6 as soon as I get time.

**Comment by amirnoxik** [comment]
okeey thank you very much i will try with 3.5

**Comment by amirnoxik** [comment]
hi 
i just run it on 3.5 
the arguments prblm disappear
but now 
after trying to login..
i get this
<a href="https://ibb.co/iQuAQk"><img src="https://preview.ibb.co/nkWDd5/Sans_titre.png" alt="Sans_titre" border="0"></a>

**Comment by amirnoxik** [comment]
node.js  ?

**Comment by amirnoxik** [comment]
i installed node.js and it's working :o :o 👍 
thanx

**Comment by Xonshiz** [comment]
AH, yes. You now need `node.js` to run this. `cfscrape` uses nodejs. I completely forgot. Thank you for reminding, I have to update this. But, if you use the windows binary that's uploaded right now, you wouldn't need node.js ;)

**Comment by amirnoxik** [comment]
oh yeah sure ... anyway thank you for everything *o*
