### ISSUE TITLE
[Request]Could you please make a windows binary for the latest commit?

### ISSUE THREAD

**Issue by Abu3safeer** [Xonshiz/anime-dl#51]
Hello my friend,
Could you please make a Windows binary for the latest commit? 

Thank you.

**Comment by Xonshiz** [comment]
You should see it by EOD.

**Comment by Abu3safeer** [comment]
Okey, Thank you, I will be waiting for it.

**Comment by Xonshiz** [comment]
Done. Check the latest release.

**Comment by Abu3safeer** [comment]
Looks like there is something wrong with the code, thought I followed the documentations here:
https://mkvtoolnix.download/doc/mkvmerge.html#mkvmerge.description.language
```
frame=34377 fps=142 q=-1.0 Lsize= 1050011kB time=00:23:53.90 bitrate=5998.8kbits/s speed=5.93x
video:1026315kB audio:22405kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.123118%
mkvmerge v21.0.0 ('Tardigrades Will Inherit The Earth') 64-bit
Erro: No language specified in '--language eng'.
```

I am not sure what causes this issue, looks like I should install python and try to play with the code.

**Comment by Abu3safeer** [comment]
For now you can hide the latest release until this is fixed.

**Comment by Abu3safeer** [comment]
By the way is it possible to show the executed code of mkvmerge, so I can try it?
