### ISSUE TITLE
I can't download an anime because of the title.

### ISSUE THREAD

**Issue by xxxKaiserxxx** [Xonshiz/anime-dl#6]
Hello,

First, Thank you so much for creating this amazing script <3

I'm trying to download this anime from crunchyroll:

http://www.crunchyroll.com/worldend-what-do-you-do-at-the-end-of-the-world-are-you-busy-will-you-save-us

But whenever I press enter I get [Errno 22].

I'm using this command:

anime-dl.exe -i "http://www.crunchyroll.com/worldend-what-do-you-do-at-the-end-of-the-world-are-you-busy-will-you-save-us/episode-1-733675" -u "xxxx" -p "xxxx" -r "1080"

This is the error I get after I press enter:

![anime-dl-issue](https://cloud.githubusercontent.com/assets/27362562/24967340/6cc87338-1fb2-11e7-964a-eb2945f73d5a.PNG)

I tried to download 1 episode and the whole series and I got the same error, I think your script can't process the long title or something.

I have downloaded many episodes just fine and this is the 1st anime that I have issue with.

Thank you again.

**Comment by Xonshiz** [comment]
From looking at the name of the episode, my best guess would be either of these 2 things : 

1.) File has "?" in it. Special characters NOT writable.

2.) File name is too long.

I'll look into this.

**Comment by xxxKaiserxxx** [comment]
Yeah, it has the both. (long and '?')

**Comment by Xonshiz** [comment]
I'll try to fix it soon, hopefully in a day or two.

**Comment by Xonshiz** [comment]
This should be fixed now. If it still causes problem, comment here and I'll re-open this.
