### ISSUE TITLE
ImportError: No module named 'crunchyroll'

### ISSUE THREAD

**Issue by matiasx1998** [Xonshiz/anime-dl#71]
Hello,
I got error when trying to call script.

`
C:\Users\Matias\Desktop\anime_dl>python __main__.py -i "http://www.crunchyroll.com/i-cant-understand-what-my-husband-is-saying/episode-13-happy-days-678059" -u "XXX" -p "XXX"
Traceback (most recent call last):
  File "__main__.py", line 8, in <module>
    from AnimeDL import *
  File "C:\Users\Matias\Desktop\anime_dl\AnimeDL.py", line 8, in <module>
    import sites
  File "C:\Users\Matias\Desktop\anime_dl\sites\__init__.py", line 1, in <module>
    import crunchyroll
ImportError: No module named 'crunchyroll'

C:\Users\Matias\Desktop\anime_dl>pause
Presione una tecla para continuar . . .
`

`C:\Users\Matias>python
Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

`

Thanks

**Comment by Xonshiz** [comment]
Please try with python 2, if possible. There seems to be this issue with python 3

**Comment by Xonshiz** [comment]
Hello, check the updated binary.
