### ISSUE TITLE
Video Unavailable

### ISSUE THREAD

**Issue by aspablo** [Xonshiz/anime-dl#72]
anime-dl.exe -i https://www.crunchyroll.com/senran-kagura-shinovi-master/episode-7-well-meet-again-778020 -u ****************** -p ******** -r 480p
Trying to login...
Logged in successfully...
Seems like this video isn't available...
'NoneType' object has no attribute 'group'

I am able to get subtitles and some other anime. I can even play the video in the browser. But anime-dl isn't able to capture it. 

Here is the link to the Error log file
https://pastebin.com/BFFQbTkv

**Comment by Xonshiz** [comment]
Hello, check the updated binary.
