### ISSUE TITLE
Could not find the requested resolution [crunchyroll.py - Line 278]

### ISSUE THREAD

**Issue by Abu3safeer** [Xonshiz/anime-dl#91]
Looks like something changed in the m3u8 file.

![image](https://user-images.githubusercontent.com/12091003/54655186-fe810780-4ad1-11e9-80ee-876a866f1e63.png)

https://github.com/Xonshiz/anime-dl/blob/master/anime_dl/sites/crunchyroll.py#L278

**Comment by axipher** [comment]
@Nicnl have you had a chance to clean up your fix for this issue to submit it on here?  this may be the same issue that you helped me solve with modified version you compiled locally on your own computer.

**Comment by Abu3safeer** [comment]
This issue only appeared with me yesterday, so I really don't know what happened exactly, I checked error-log and everything seems fine.

I think developers of Python might notice something I don't see.

**Comment by axipher** [comment]
I'm trying that show now, episode 1 of the English dub is downloading fine, I'll see what it does when it gets to episode 12.

Just so that I'm trying this on the same episode as you, is that episode 12 form one of the Dubs, or the main show?

**Comment by Abu3safeer** [comment]
https://www.crunchyroll.com/rokka-braves-of-the-six-flowers-

**Comment by Abu3safeer** [comment]
![image](https://user-images.githubusercontent.com/12091003/54682799-f308fd00-4b20-11e9-920e-d4480340d46e.png)
It download the subtitle and stop on video.

**Comment by axipher** [comment]
Maybe the show has different options in different regions.  I get all these options when I go to that show.  It looks like your issue is on the main show itself and not the English Dub.  Once I finish downloading the English Dub, I'll try the regular show.

    Rokka -Braves of the Six Flowers-
    Rokka -Braves of the Six Flowers- (Spanish Dub)
    Rokka -Braves of the Six Flowers- (German Dub)
    Rokka -Braves of the Six Flowers- (French Dub)
    Rokka -Braves of the Six Flowers- (Portuguese Dub)
    Rokka -Braves of the Six Flowers- (English Dub)

**Comment by Abu3safeer** [comment]
I don't watch dub, only Japanese audio with Arabic subtitle, but video is not downloaded.

**Comment by axipher** [comment]
So I was able to download all 12 episode of both the English Dub and the Japanese.

Nicnl had made some fixes to his offline copy and was waiting to see if they worked and when he had time to put them up on here.

Shoot me an email to the email in my Bio on here if you need a copy of one of the episodes in the mean time.

**Comment by Abu3safeer** [comment]
Actually I don't need that anime in specific, I just want to fix the issue.

**Comment by Nicnl** [comment]
Hey @Abu3safeer 

I wrote a few fixes a week ago  
You can access the source code here: https://github.com/Nicnl/anime-dl/commits/master

I initially sent Facebook messages to @Xonshiz asking him if he could add me as an official contributor so that I could push bug fixes without bothering him  

But I don't have any responses yet, so...  
In the meantime, here is a compiled version, it would be great if you could tell me if it fixes your issue  
- [anime-dl.exe](https://download.nicnl.com/b81c05b1ce5631d5d486b75eab092c2528e80336de1f0cef86aa66228d934875379acb7877181f985ef65296da319f8750b6c8b5f3eef7403506035a6b72c876-1e43938557a84035654b6325e16803389/anime-dl.exe)

**Comment by Abu3safeer** [comment]
![image](https://user-images.githubusercontent.com/12091003/54723198-d3e98a00-4b77-11e9-9620-9a7da00627c2.png)

It still skips the video:
![image](https://user-images.githubusercontent.com/12091003/54723214-e19f0f80-4b77-11e9-90d7-813171b3f886.png)

**Comment by Abu3safeer** [comment]
Looks like the issue is only with Rokka anime.
![image](https://user-images.githubusercontent.com/12091003/54723402-7dc91680-4b78-11e9-8dea-f1a918edbb73.png)

**Comment by Abu3safeer** [comment]
After some tests I recognized that this issue appeares with "English" links, when there is no language in the url:
https://www.crunchyroll.com/the-rising-of-the-shield-hero/episode-11-catastrophe-returns-781158
but if there is a language in the url it would work normally.
https://www.crunchyroll.com/ar/the-rising-of-the-shield-hero/episode-11-catastrophe-returns-781158

if I deduct the language, it will return something like "type of non-object".

**Comment by axipher** [comment]
@Abu3safeer That is the same thing I already identified in [issue #86](https://github.com/Xonshiz/anime-dl/issues/86)

Did you try the new version of the EXE provided by @Nicnl?  It works for the English links fine.

**Comment by Abu3safeer** [comment]
Yes, he has linked his new exe above your comment, I am doing it with it.
