### ISSUE TITLE
GTO cannot be downloaded, because of the aspect ratio.

### ISSUE THREAD

**Issue by Abu3safeer** [Xonshiz/anime-dl#96]
Hello everyone,

I tried to download GTO with 1080p but as you might know GTO is very old anime the highest resolution is 480p, but it has different aspect ratio so it is not downloadable at all.

**Comment by Abu3safeer** [comment]
I wanted to create this issue in your for @Nicnl but there is no Issues option.

**Comment by Xonshiz** [comment]
I'll take a look at this. I remember downloading GTO from anime-dl earlier. Will check again. Aspect ratio shouldn't cause any problems though.

**Comment by Abu3safeer** [comment]
Hello @Xonshiz , Is the fixed in https://github.com/Xonshiz/anime-dl/releases/tag/2019.05.26

**Comment by EpicUnknown** [comment]
Is your resolution 640x480? If so I just requested a pull request that will fix this issue.
