### ISSUE TITLE
AttributeError: module 'crunchyroll' has no attribute 'Crunchyroll'

### ISSUE THREAD

**Issue by sh-hugo** [Xonshiz/anime-dl#99]
```
Traceback (most recent call last):
  File "./__main__.py", line 16, in <module>
    class Main():
  File "./__main__.py", line 73, in Main
    logger=logger, episode_range=args.range)
  File "/root/project/anime-dl/anime_dl/Anime_dl.py", line 28, in __init__
    sites.crunchyroll.Crunchyroll(
AttributeError: module 'crunchyroll' has no attribute 'Crunchyroll'

```

**Comment by Xonshiz** [comment]
Hey, can you please mention what is your operating system? And also, the python version.

**Comment by Watashis** [comment]
I have the same problem 
![Image](https://i.imgur.com/JenBsH7.png)

**Comment by Xonshiz** [comment]
Got it. The imports will be different for python 3. This should still work for Python 2. I think I'll just port it to Python 3.

**Comment by Watashis** [comment]
`ImportError: No module named anime_d`
![Image](https://i.imgur.com/4xdCO7R.png)

**Comment by Xonshiz** [comment]
Wow, WTH! My Pycharm has been lying to me. I'll check this out and push an update in a while then. Sorry for the mess, folks.

**Comment by Watashis** [comment]
Well, we are waiting, but thanks for the work anyway.


(I don't know English, sorry)
